# Generated by Django 2.1.7 on 2019-08-25 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorToExhibit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(choices=[('A', 'Author'), ('B', 'Exhibit'), ('C', 'Exhibition'), ('D', 'Gallery')], max_length=1)),
                ('jsonString', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(choices=[('A', 'Author'), ('B', 'Exhibit'), ('C', 'Exhibition'), ('D', 'Gallery')], max_length=1)),
                ('jsonString', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='gallery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Gallery'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='exhibition_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Exhibition'),
        ),
        migrations.AddField(
            model_name='description',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Language'),
        ),
        migrations.AddField(
            model_name='authortoexhibit',
            name='exhibit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Exhibit'),
        ),
    ]
