# Generated by Django 2.1.7 on 2019-05-11 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=255)),
                ('art_description', models.TextField()),
                ('art_img', models.ImageField(upload_to='art_images/')),
                ('art_audio', models.FileField(upload_to='art_audios/')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_img', models.ImageField(blank=True, null=True, upload_to='artist_images/')),
                ('artist_name', models.CharField(max_length=70)),
                ('artist_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guidexpuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('1', 'Superuser'), ('2', 'Admin'), ('3', 'Worker')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorise_exhibition', to='guideXP_admin.Guidexpuser'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='exhibition_uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_exhibition', to='guideXP_admin.Guidexpuser'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorise_artist', to='guideXP_admin.Guidexpuser'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_artist', to='guideXP_admin.Guidexpuser'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='art_authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorise_art', to='guideXP_admin.Guidexpuser'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='art_from_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideXP_admin.Artist'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='art_in_exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guideXP_admin.Exhibition'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='art_uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_art', to='guideXP_admin.Guidexpuser'),
        ),
    ]
