# Generated by Django 2.1.7 on 2019-05-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideXP_admin', '0003_auto_20190510_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='exhibition_descrip',
            new_name='exhibition_description',
        ),
    ]
