# Generated by Django 2.1.7 on 2019-05-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideXP_admin', '0004_auto_20190510_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_authorised_by',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_uploaded_by',
        ),
        migrations.RemoveField(
            model_name='artimage',
            name='art_in_gallery',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='exhibition_description',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='exhibition_end',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='exhibition_gallery',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='exhibition_start',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
