# Generated by Django 2.2.4 on 2019-08-25 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(choices=[('A', 'Author'), ('B', 'Exhibit'), ('C', 'Exhibition'), ('D', 'Gallery')], max_length=1)),
                ('jsonString', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exhibition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(choices=[('A', 'Author'), ('B', 'Exhibit'), ('C', 'Exhibition'), ('D', 'Gallery')], max_length=1)),
                ('jsonString', models.TextField()),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Language')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorToExhibit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Author')),
                ('exhibit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gxpadmin.Exhibit')),
            ],
        ),
    ]
