# Generated by Django 2.1.7 on 2019-05-04 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190504_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='approve_type',
            field=models.CharField(choices=[('1', 'approved'), ('0', 'not approved')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='img',
            name='content',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AddField(
            model_name='img',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='img',
            name='uploder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='user_catagory',
            field=models.CharField(choices=[('1', 'superuser'), ('2', 'admin'), ('3', 'uploader')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Gallery'),
        ),
    ]
