# Generated by Django 2.1.7 on 2019-05-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190504_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='img',
            name='approve_type',
        ),
        migrations.RemoveField(
            model_name='img',
            name='uploder',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_catagory',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
