# Generated by Django 2.1.7 on 2019-05-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190504_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='content',
        ),
        migrations.RemoveField(
            model_name='img',
            name='title',
        ),
    ]
