# Generated by Django 2.1.7 on 2019-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190504_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='uploader',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.FileField(upload_to='images'),
        ),
    ]
